### ISSUE TITLE
A user can view featured sports equipment listings.

### ISSUE THREAD

**Issue by kagranger** [kagranger/sports-exchange#1]
**Tasks**
- [x] Create a wireframe.
- [x] Document the data model.
- [x] Document the component hierarchy.
- [x] Build CardWrapper and Card components.
- [x] Add inverse data flow. 
- [x] Add CSS styling using Bootstrap.

**Data Model**
```javascript
{
    items : [
        {
            sport: "Baseball/Softball",
            image: "https://baseballmonkey.nexcesscdn.net/media/catalog/product/cache/5/thumbnail/600x/9df78eab33525d08d6e5fb8d27136e95/m/i/mizuno-312378-pro-limited-edition-gmp400j-adult-baseball-glove.jpg",
            product: "Mizuno Baseball Glove (13-15yrs)"
        },
        {
            sport: "Golf",
            image: "https://s3-media3.fl.yelpcdn.com/bphoto/dchFHUURc13l2uhdee0WXg/ls.jpg",
            product: "Adams IdeaPro 18 degree Hybrid Golf Club (19+yrs)"
        },
        ...
    ]
}
```

**Component Hierarchy**
```javascript
<CardsWrapper>
    <Card Sport Image Product />
</CardsWrapper>
````

**Wireframe**
![screen shot 2018-03-27 at 2 51 29 pm](https://user-images.githubusercontent.com/36418379/37996982-67ef0fd2-31ce-11e8-98a3-f29ba1e6ac37.png)

![screen shot 2018-03-28 at 3 53 49 pm](https://user-images.githubusercontent.com/36418379/38060654-88a1f8a2-32a0-11e8-8619-196ff65c12f1.png)

**Comment by kagranger** [comment]
![screen shot 2018-03-27 at 2 17 12 pm](https://user-images.githubusercontent.com/36418379/37995549-b53eb238-31c9-11e8-9f5c-738e077c93c8.png)
